### ISSUE TITLE
Sort out some default BSC extras

### ISSUE THREAD

**Issue by ethanjohnstone** [ethanjohnstone/genesis#10]
eg. 

- [ ] Google site search
- [ ] Simple blog holder/ blog entries
- [ ] GalleryPage

**Comment by NikxDa** [comment]
Does this make sense for a generic template, or would it be better off in the info repository as a snippet?

**Comment by ethanjohnstone** [comment]
Plan is for them to be packages and just to require them with composer similar to other packages during the install script
