### ISSUE TITLE
Remove additional formatting options blocks

### ISSUE THREAD

**Issue by Bookmonkey** [ethanjohnstone/genesis#8]
Looks like new version of SS 4 includes a new set of options for formatting. We ideally only want to show our styles. 

Add to /app/_config.php
``` php
use SilverStripe\Forms\HTMLEditor\TinyMCEConfig;
 $formats = [];
 // Custom editor styles	// Custom editor styles
TinyMCEConfig::get('cms')
->addButtonsToLine(1, 'styleselect')
->setOptions([
        'importcss_append' => true,
        'style_formats' => $formats
]); 
```

**Comment by NikxDa** [comment]
@Bookmonkey Could you pull the outstanding 20 commits from this one onto your fork & then open a PR? I was about to get started on this stuff & would love to have your latest changes before doing so.
